### ISSUE TITLE
Add test to ensure app requirements are complete

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/software-development-handbook#12]
In a recent release the app now requires `importlib.metadata`.

Currently this is installed in [requirements_dev.txt](https://github.com/open-contracting/cove-oc4ids/blob/3e1c74b40e7b041541d1c7bd8edd90a77abfe0f9/requirements_dev.txt#L30) but not in requirements.txt.

Without manually installing `importlib-metadata` the app errors on start up, as follows:

```Traceback (most recent call last):
  File "/home/cove/cove/.ve/lib/python3.6/site-packages/bootstrap3/__init__.py", line 8, in <module>
    from importlib.metadata import metadata
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cove_project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/cove/cove/.ve/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/cove/cove/.ve/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/cove/cove/.ve/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/cove/cove/.ve/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/cove/cove/.ve/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/cove/cove/.ve/lib/python3.6/site-packages/bootstrap3/__init__.py", line 10, in <module>
    from importlib_metadata import metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by jpmckinney** [comment]
I forgot: A major reason for separating dev dependencies is that a maintainer can very confidently remove dev dependencies (as long as tests pass, no problem!), whereas a maintainer needs to be more careful when removing app dependencies (e.g. tests might still pass if coverage is low).

In my experience, I also see a tendency for requirements to balloon (even when no longer needed) when dev and app dependencies are mixed – partly for the above reason, where a maintainer might see a package in the requirements that they suspect is no longer needed, but it's too much effort to check.

To my knowledge, this issue has only been encountered by @michaelwood, and I'm not sure how it occurs, because using `pip-compile; pip-compile requirements_dev.in` [as documented](https://ocp-software-handbook.readthedocs.io/en/latest/python/applications.html#requirements), has never caused a problem in my work.

So, I'm re-focusing the issue to be about adding this for Django apps, to protect against any such mistakes:

```yaml
- run: pip install -r requirements.txt
- run: ./manage.py --help
```

**Comment by jpmckinney** [comment]
Done in all Django apps.
